apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db-demo
spec:
  selector:
    matchLabels:
      type: db
      service: deploy-db-demo
  template:
    metadata:
      labels:
        type: db
        service: deploy-db-demo
        vendor: MongoLabs
    spec:
      containers:
        - name: db
          image: mongo:3.3
          ports:
            - containerPort: 28017

---

apiVersion: v1
kind: Service
metadata:
  name: deployment-db-demo
spec:
  ports:
  - port: 27017
  selector:
    type: db
    service: deploy-db-demo
