apiVersion: v1
kind: Pod
metadata:
  name: multi-containers-in-a-pod-demo
  labels:
    type: stack
spec:
  containers:
    - name: db
      image: mongo:3.3
    - name: api
      image: vfarcic/go-demo-2
      env:
        - name: DB
          value: localhost
      livenessProbe:
        httpGet: # HTTP probe type
          path: /this/path/does/not/exist
          port: 8080
        initialDelaySeconds: 5 # the probe should be delayed by five seconds
        timeoutSeconds: 2 #  The requests should timeout after two seconds, Defaults to 1
        periodSeconds: 5 # the process should be repeated every, Defaults to 10
        failureThreshold: 1 # how many attempts it must try before giving up, Defaults to 3