apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-demo
spec:
  replicas: 2
  selector: #  to select which Pods should be included in the ReplicaSet.
    matchLabels:
      type: backend
      service: ReplicaSet-demo
  template:
    metadata:
      labels:
        type: backend
        service: ReplicaSet-demo
        db: mongo
        language: go
    spec:
      containers:
      - name: db
        image: mongo:3.3
      - name: api
        image: vfarcic/go-demo-2
        env:
        - name: DB
          value: localhost
        livenessProbe:
          httpGet:
            path: /demo/hello
            port: 8080