apiVersion: v1
kind: Service
metadata:
  name: service-demo
spec:
  type: NodePort # ClusterIP is the default
  ports:
    - port: 28017
#      nodePort: 30001 # make it random
#      protocol: TCP # TCP is the default
  selector: #  to know which Pods should receive requests
    type: backend
    service: ReplicaSet-demo